mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from sistemabio import views

urlpatterns = [
    path("sistemabio/", include("sistemabio.urls")),
   #  path('',views.loggin),
    path("admin/", admin.site.urls),
   # path ("admin/loggin/",views.loggin)

]

mysite/sistemabio/urls.py
from django.urls import path

from . import views

app_name = "sistemabio"
urlpatterns = [
    path("",views.index, name="home"),
    path("signup/",views.signup, name="signup"),
    path("signin/",views.signin, name="signin"),
    path("logout/",views.signout,name="logout"),
    path("about/",views.about, name="about"),
    path("principal/",views.principal, name="principal"),

    #Inquilinos
    path("inquilinosinicial/", views.inquilinosinicial, name="inquilinosinicial"),
    path("inquilinos/",views.inquilinos, name="inquilinos"),
    path("new_inquilino/",views.new_inquilino, name="new_inquilino"),
    path("search_inquilino/",views.search_inquilino, name="search_inquilino"),
    # path("search_inquilino/<int:inquilino_para>",views.search_inquilino, name="search_inquilino"),
    path("detail_inquilino/<int:usuario_id>/",views.detail_inquilino, name ="detail_inquilino"),
    path("delete_inquilino/<int:inquilino_id>/", views.delete_inquilino, name="delete_inquilino"),
    

    #Visitantes

    #Trabajadores


    
] 
   

mysite/sistemabio/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils import timezone


from django.contrib import admin
# Create your models here.

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ap_paterno = models.CharField(max_length=15)
    ap_materno = models.CharField(max_length=15)
    #   user = models.ForeignKey(User)
    curp = models.CharField(max_length=30)
     # domicilio
    piso = models.IntegerField()
     # type: Number,
    departamento = models.IntegerField()
     # type: Number,
    telefono = models.CharField(max_length=15)
     # type: String, models.IntegerField()
    correo = models.EmailField()
    #  type: String,
    fecha_nac = models.DateField()
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    # Campos con opciones
    CATALOGO_PERFIL = [
        ('1', 'Administrador'),
        ('2', 'Usuario Inquilino'),
        ('3', 'Usuario Visitante'),
        ('4', 'Usuario Trabajador'),
    ]
    id_perfil = models.CharField(max_length=2, choices=CATALOGO_PERFIL, default='2')
    # Campos con opciones
    CATALOGO_STATUS = [
        ('1', 'ALTA/COMPLETO'),
        ('2', 'BAJA'),
        ('3', 'PENDIENTE'),
        ('4', 'ALTA/COMPLETO'),
    ]
    id_status = models.CharField(max_length=2, choices=CATALOGO_STATUS, default='3')

    def __str__(self):
        return self.nombre


# class Usuario_Sesion(models.Model):
#     id_sesion = models.AutoField(primary_key=True)
#     id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     CATALOGO_TIPO_SESION = [
#         ('1', 'FACIAL'),
#         ('2', 'VOZ'),
#         ('3', 'HUELLA'),
#         ('4', 'NORMAL'),
#     ]
#     id_tipo_sesion = models.CharField(max_length=2, choices=CATALOGO_TIPO_SESION, default='4')
#     CATALOGO_STATUS_SESION = [
#         ('0', 'NO REGISTRADO'),
#         ('1', 'REGISTRADO'),
#     ]
#     id_status_sesion = models.CharField(max_length=2, choices=CATALOGO_STATUS_SESION, default='0')


# class Usuario_Tipo_Sesion(models.Model):
#     id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     id_tipo_sesion = models.ForeignKey(Usuario_Sesion, on_delete=models.CASCADE)
#     image = models.BinaryField()

mysite/sistemabio/forms.py
from django.forms import ModelForm
from .models import Usuario

class InquilinoForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['nombre','ap_paterno','ap_materno', 'curp','piso','departamento','telefono', 'correo', 'fecha_nac', 'id_perfil', 'id_status']

mysite/sistemabio/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect,HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader
#creatiionform
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Usuario
from .forms import InquilinoForm


#Administrador e Index
def index(request):
     title='Index'
    # return HttpResponse("Hello, world. You're at the polls index.")
     return render (request,"sistemabio/index.html",{
          'mytitle':title
     })
     
def signup(request):
        if request.method == 'GET':
            print('enviando formulario')
            title='Registrar'
            return render(request, "sistemabio/signup.html",{
                'mytitle':title,
                'form':UserCreationForm
            } ) 
        else:
             if request.POST["password1"] == request.POST["password2"]:
                  #register user
                  try:
                    user = User.objects.create_user(username=request.POST["username"],
                                                   password=request.POST["password1"])
                    user.save()
                    login(request, user)
                    return redirect('/sistemabio/principal/')
                   # return HttpResponse('User creado satisfactoriamente')        
                  except IntegrityError:
                       return render(request, "sistemabio/signup.html",{
                            'error': 'El user ya existe',
                            'form':UserCreationForm
                        } ) 
             return render(request, "sistemabio/signup.html",{
                            'error': 'Passwords no coinciden',
                            'form':UserCreationForm
                        } )   
 

   #return render(request, "sistemabio/signin.html",
def signin(request):
         if request.method == "GET":
            title='Iniciar sesion'
            return render(request, "sistemabio/signin.html",{
                'mytitle':title,
                'form':AuthenticationForm
            } )        
         else:
              user = authenticate( request, username=request.POST['username'], password=request.POST['password'])
              if user is None:
                return render(request, 'sistemabio/signin.html',{
                    'error': "usuario o password es incorrecto.",
                    'form': AuthenticationForm
                    })

              login(request, user)
              return redirect('/sistemabio/principal/')
            
   #return render(request, "sistemabio/signin.html",
@login_required
def principal(request):
     title='Principal Administrador'
     return render (request,"sistemabio/principal.html",{
          'mytitle':title
     })
@login_required
def signout(request):
     logout(request)
     return redirect('/sistemabio/signin/')
def about(request):
     title='About'
     return render (request,"sistemabio/about.html",{
          'mytitle':title
     })

#Inquilinos
def inquilinosinicial(request):
     title='Inquilinos Inicial'
     return render (request,"sistemabio/inquilinos/inquilinos_inicial_copy.html",{
          'mytitle':title
     })
def inquilinos(request):
     inquilinos = Usuario.objects.all()
     title='Inquilinos'
     return render (request,"sistemabio/inquilinos/all-inquilinos.html",{
          'mytitle':title,
          'inquilinos':inquilinos
     })

def new_inquilino(request):
     if request.method == "GET":
        return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        try:
            form = InquilinoForm(request.POST)
            new_inquilino = form.save(commit=False)
            new_inquilino.save()
            return redirect('/sistemabio/inquilinos/')
        except ValueError:
            return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm, "error": "Error creando el inquilino."})
def search_inquilino(request):
     busqueda = request.POST.get("buscar")
     print('nusqueda es ',busqueda)
     nombre = request.POST.get("nombre")
     print('nombre es ',nombre)
     piso = request.POST.get("piso")
     print('npiso es ',piso)
     departamento = request.POST.get("departamento")
     print('ndepartamento es ',departamento)
     inquilinos = Usuario.objects.all()
     if busqueda:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = busqueda) | 
            Q(nombre__icontains = busqueda) |
            Q(curp__icontains = busqueda) |
            Q(departamento__icontains = busqueda)
        ).distinct()  
     if nombre:
        inquilinos = Usuario.objects.filter(
            Q(nombre__icontains = nombre) 
        ).distinct()  
        print('nombre des ',nombre)
     if piso:
        inquilinos = Usuario.objects.filter(
            Q(piso__icontains = piso) 
        ).distinct() 
        print('npiso des ',piso) 
     if departamento:
        inquilinos = Usuario.objects.filter(
            Q(departamento__icontains = departamento)
        ).distinct() 
        print('ndepartamento des ',departamento)
        print('inquilino es ',inquilinos)
    # inquilino = get_object_or_404(Usuario,pk=inquilino_para)
    #  inquilinos = Usuario.objects.filter(nombre='jessica sanchez pruebaF5')
     title='search'
     return render (request,"sistemabio/inquilinos/s-inquilinos.html",{
          'mytitle':title,
          'inquilinos':inquilinos
     })
#     
def detail_inquilino(request, usuario_id):
    inquilino = get_object_or_404(Usuario,pk=usuario_id)
    print('usuario id ', usuario_id)
    title='detail'
    return render(request,"sistemabio/inquilinos/detail-inquilino.html",{
        'mytitle':title,
        'inquilino':inquilino
    })

def delete_inquilino(request, inquilino_id):
    inquilino = Usuario.objects.get( id_usuario=inquilino_id)
    if request.method == 'POST':
        inquilino.delete()
        return redirect('/sistemabio/inquilinos/')

mysite/sistemabio/templates/sistemabio/inquilinos/all-inquilinos.html
{% extends "sistemabio/base.html" %}

{% block content %}

    <header class="row" style="position: relative; height: 50vh; width: 100%;">
        <div
              class="col s12 m11 l9 xl8 "
              style="position: absolute; top: 0px; height: 120%; left: 0px; right: 40px; width: 100%;"
            >
            <img alt="" src="/img/ba5_1.png" 
                    style="position: absolute; right: -12px; top: 20%; width: 100%; height:80%"
                >
            <img alt="" src="/img/ba6_1.png"
                    style="position: absolute;  right: -12px; top: 0px; width: 100%; height:90%">
        </div>
        <div class="col s4 hide-on-small-only" 
            
             style="position: absolute; top: 70%; left: 80%; height: 100%; transform: translate(-50%, -50%); width: 30%;" 
        >
            <h1 class="titulo" style="font-size:40px">
              LISTADO DE <b>INQUILINOS</b>
            </h1>
            <blockquote>
              <h4 class="subtitulo black-text" style="font-size:20px">
                <b>
                  Aquí puedes consultar los registros <br /> de los Inquilinos
                </b>
              </h4>
            </blockquote>
        </div>
 <!--style="height: 100%; position: absolute; top: 0%; right: 0%;"
 style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
 -->
        <div class=" col s12 m9 l9 xl8 white-text" style="height: 100%; position: absolute; top: 0%; right: 50%;">
          <img alt="" src="/img/parteba15_2.png" 
          class="responsive-img" style="position: absolute; right: 0px; top: 0px; height: 120%; width: 50%;">
        </div>  
    </header>
      <br />
      <br />
      <br />
      <div class="row justify-content-end">
        <div class="col-3 align-self-end">
          <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134); border-radius: 20px;"
                    href="javascript:window.history.back(); " 
                > 
            <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
            </i>       Regresar              
          </a>
        </div>
      </div>
    
      <!--div class="row justify-content-end">
        <div class="col-3 align-self-end">
        <button class="btn btn-success text-center btn p-2 " onclick="window.history.back()">
          <span class="material-symbols-rounded btn p-2  text-center text-white">
              arrow_back
          </span> Regresar 
        </button>
        </div>
      </div-->  
      
  <div class="container p-5">
        <h3 style="font-family: 'Franklin Gothic Medium'">Inquilinos registrados</h3>
         <!--h1 class="bg-info">Hola {{Administrador.name}}</h1-->
    <div class="row justify-content-end">
      <div class="col-3 align-self-center">
        <a class="btn btn-outline-info text-center" style=" background-image: var(--bs-gradient);border-radius: 20px;"
           href="/sistemabio/new_inquilino" 
        >
          <p style="font-family: 'Franklin Gothic Medium'" >
            Añadir inquilino <i class="material-icons rounded-circle ">person_add</i>
          </p>
        </a>
      </div>
    </div>        

  <div class="row" style=" border: 0.5px solid rgb(1, 17, 135); margin: 25px 0px; background:rgb(144, 221, 227)">
    
<!---->
{% for inquilino in inquilinos %}
  <div class="col-md-3">
    <br>
      <div class="card" style=" border: 0.3px solid rgb(64, 113, 247);  ">
        <div class="card-body ">
           <h3 class="d-flex p-2 flex-row-reverse">
            <a href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}">Detail<i class="fas fa-edit"></i></a> 
           </h3>
           Inquilino:
          <h4 class="card-title ">
           {{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}
          </h4>
          <p>Curp: {{ inquilino.curp }} </p>
          <p>No. Piso: {{ inquilino.piso }} </p>
          <p>No. Departamento: {{ inquilino.departamento }} </p>
          <p>No. Teléfono: {{ inquilino.telefono }} </p>
          <p>Correo: {{ inquilino.correo }} </p>
          <h1>Datos Biométricos</h1>
          <div class="container p-2">
               <div class="row">
                <h4>Rostro</h4>
                <div class="col-md ">
                   <div class="card-columns">
                      <div class="card animated fadeInDown">
                        <img src={{rostro.path}} class="card-img-top" alt="">
                            <div class="card-body">
                                  <h5 class="card-title">Nombre: {{rostro.originalname}}</h5>
                                     <!--p class="card-text">Nombre en bd:{{rostro.filename }}</p-->
                                      <p>fecha: {{rostro.date|date:'M j Y:i'}}</p>
                                          
                            </div>
                       </div>
                                 
                     </div>
                 </div>
                </div>
          </div>
        </div>
      </div>
    <br>
  </div>
{% endfor %}
  
</div>
</div>

{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/detail-inquilino.html
{% extends "sistemabio/base.html" %}

{% block content %}

    <header class="row" style="position: relative; height: 50vh; width: 100%;">
        <div
              class="col s12 m11 l9 xl8 "
              style="position: absolute; top: 0px; height: 120%; left: 0px; right: 40px; width: 100%;"
            >
            <img alt="" src="/img/ba5_1.png" 
                    style="position: absolute; right: -12px; top: 20%; width: 100%; height:80%"
                >
            <img alt="" src="/img/ba6_1.png"
                    style="position: absolute;  right: -12px; top: 0px; width: 100%; height:90%">
        </div>
        <div class="col s4 hide-on-small-only" 
            
             style="position: absolute; top: 70%; left: 80%; height: 100%; transform: translate(-50%, -50%); width: 30%;" 
        >
            <h1 class="titulo" style="font-size:40px">
              DETALLE DE <b>INQUILINOS</b>
            </h1>
            <blockquote>
              <h4 class="subtitulo black-text" style="font-size:20px">
                <b>
                  Aquí puedes consultar los datos registrados<br /> por Inquilino
                </b>
              </h4>
            </blockquote>
        </div>
 
        <div class=" col s12 m9 l9 xl8 white-text" style="height: 100%; position: absolute; top: 0%; right: 50%;">
          <img alt="" src="/img/parteba15_2.png" 
          class="responsive-img" style="position: absolute; right: 0px; top: 0px; height: 120%; width: 50%;">
        </div>  
    </header>
      <br />
      <br />
      <br />
      <div class="row justify-content-end">
        <div class="col-3 align-self-end">
          <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134); border-radius: 20px;"
                    href="javascript:window.history.back(); " 
                > 
            <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
            </i>       Regresar              
          </a>
        </div>
      </div> 
      
  <div class="container p-5">
        <h3 style="font-family: 'Franklin Gothic Medium'">Inquilinos registrados</h3>
         <!--h1 class="bg-info">Hola {{Administrador.name}}</h1-->
    <div class="row justify-content-end">
      <div class="col-3 align-self-center">
        <a class="btn btn-outline-info text-center" style=" background-image: var(--bs-gradient);border-radius: 20px;"
           href="/sistemabio/new_inquilino" 
        >
          <p style="font-family: 'Franklin Gothic Medium'" >
            Añadir inquilino <i class="material-icons rounded-circle ">person_add</i>
          </p>
        </a>
      </div>
    </div>        

  <div class="row" style=" border: 0.5px solid rgb(1, 17, 135); margin: 25px 0px; background:rgb(144, 221, 227)">
<!---->
  <div class="col-md">
    <br>
    <!-- <div class="card" style=" border: 1.3px solid rgb(64, 113, 247);  "> -->
      <div class="card-body ">
         <h3 class="d-flex p-2 flex-row-reverse">
            <a href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}"><i class="fas fa-edit"></i></a> 
         </h3>
         Inquilino:
        <h4 class="card-title ">
         {{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}
        </h4>
        <p>Curp: {{ inquilino.curp }} </p>
        <p>No. Piso: {{ inquilino.piso }} </p>
        <p>No. Departamento: {{ inquilino.departamento }} </p>
        <p>No. Teléfono: {{ inquilino.telefono }} </p>
        <p>Correo: {{ inquilino.correo }} </p>
        <h1>Datos Biométricos</h1>
        <div class="container p-2">
             <div class="row">
              <h4>Rostro</h4>
              <div class="col-md ">
                 <div class="card-columns">
                    <div class="card animated fadeInDown">
                      <img src={{rostro.path}} class="card-img-top" alt="">
                          <div class="card-body">
                                <h5 class="card-title">Nombre: {{rostro.originalname}}</h5>
                                   <!--p class="card-text">Nombre en bd:{{rostro.filename }}</p-->
                                    <p>fecha: {{rostro.date|date:'M j Y:i'}}</p>
                                        
                          </div>
                     </div>
                               
                   </div>
               </div>
              </div>
        </div>
        <!-- DELETE REQUEST -->
        <form action="{% url 'sistemabio:delete_inquilino' inquilino.id_usuario %}" method="POST" >
          {% csrf_token %}
          <button class="btn btn-danger">Delete</button>
          <!-- <input type="hidden" name="_method" value="DELETE">
          <button type="submit" class="btn btn-danger btn-block ">
            <span class="material-icons me-1">delete</span>
            Eliminar
            </button> -->
        </form>
      </div>
    <!-- </div> -->
    <br>
  </div>
  
</div>
</div>

{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/inquilinos_inicial_copy.html
{% extends "sistemabio/base.html" %}

{% block content %}
<main style="position: relative; overflow: hidden; width: 100%; max-width: 1600px; margin: auto; min-height: 100vh;">
    <img src="/img/partebaa3.png" alt="" 
        style="position: absolute; width: 1016px; height: 300px; top: 0px; right: 600px; z-index: -1;"
    >
    <div class="row ">
        <div class="col s12 l6" style="padding: 0px 4%;">
            <br>
            <h1 class="header   text-white text-darken-3" 
                style="font-size: 3.1rem; font-weight: 500; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"
            >
             R & S Biométric 
            </h1>
            <h4>Inquilinos</h4>
            <br>
            <blockquote>
                <h4 class="" style="font-size: 1.7rem; font-family:'Calibri'"
                 >
                 <b>
                  Registro de información de los inquilinos del edificio de condominio
                </b> 
                </h4>
            </blockquote>
        </div>
        <div class="col s12  l6 center">
            <img class="d-block w-100" src="/img/upiita-logo.png" alt="First slide" height="200px" width="150px" >
        </div>    
    </div>
    <div class="row justify-content-end">
        <div class="col-3 align-self-end">
          <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134);border-radius: 20px;"
                    href="javascript:window.history.back(); " 
                > 
            <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
            </i>       Regresar              
          </a>
        </div>
      </div>
<div class="row" style=" border: 0.0px solid rgb(220, 220, 200); margin: 25px 0px;" > 
    <div class="col s12 m6 l6 xl6">
        <div class="MenuActionContainer text-center bg-info p-2 " style="--bs-bg-opacity: .8;">
            <!-- background:rgb(27, 158, 149) -->
            <i class="material-icons text-white  p-2" style="background:rgb(6, 127, 202); border-radius: 20px;">person</i>
            <h5 class="text-black" style="font-family:'Franklin Gothic Medium'" ><!--, sans-serif 'Franklin Gothic Medium', Arial,Arial Narrow ;"-->  
                <b>Inquilinos</b>
            </h5>
            <p class="textHeight">Aquí puedes consultar el historial de todos los registros de inquilinos, agregar nuevos y darle seguimiento...</p>
            <a class="waves-effect waves-light text-white btn p-2 text-center " style="background:rgb(6, 127, 202);border-radius: 20px;" 
                href="{% url 'sistemabio:inquilinos' %}"
            > <!--/inquilinos/all-inquilinos    "/sistemabio/inquilinos" -->
                Ver registros
                <i class="material-icons text-white btn p-2 text-center">view_list</i>
            </a>
        </div>
    </div>
    <div class="col s12 m6 l6 xl6 align-self-center">
        <div class="MenuActionContainer bg-info p-2 text-center " style="--bs-bg-opacity: .7;">
            <!-- background:rgb(94, 213, 243) -->
            <i class="material-icons text-light p-2 rounded-circle" style="background:rgb(6, 127, 202);">person_add</i>
            <h5 class="text-black" style="font-family:'Franklin Gothic Medium'" >
                <strong>Añadir Inquilino</strong>
            </h5>
            <p class="textHeight">Aquí puedes añadir la 
            <br>información básica del inquilino nuevo, así como los datos biométricos... 
            </p>
            <a class="waves-effect waves-light text-white btn p-2 text-center " style ="background:rgb(6, 127, 202);border-radius: 20px;"
                href="/sistemabio/new_inquilino" 
            >
                Añadir
                <i class="material-icons text-white rounded-circlet btn p-2 text-center ">add</i>
            </a>
        </div>
    </div>
    <div class="col s12 m6 l6 xl6">
        <div class=" MenuActionContainer text-center bg-info p-2" style=" --bs-bg-opacity: .5;" >
            <!-- background:rgb(115, 209, 212, 0.941); -->
            <i class="material-icons text-white medium  p-2 rounded-circle" style="background: rgb(6, 127, 202);">search</i>
            <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                <b>Buscar Inquilino</b>
           </h5>
            <p class="textHeight">Aquí puedes buscar un inquilino y ver su información.</p>
            <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(6, 127, 202);border-radius: 20px;"
            href="/sistemabio/search_inquilino" 
            >
                Buscar
                <i class="material-icons  text-white large rounded-circle btn p-2 text-center">person_search
                </i>                    
            </a>
        </div>
    </div>
    <div class="col s12 m6 l6 xl6">
        <div class=" MenuActionContainer text-center bg-info p-2" style="--bs-bg-opacity: .8;">
            <!-- "background: rgb(107, 234, 225)" -->
            <i class="material-icons text-white medium  p-2 rounded-circle" style="background: rgb(6, 127, 202)">receipt_long</i>
            <h5 class="text-black" style="font-family: 'Franklin Gothic Medium'" >
                <b>Generar informe de inquilinos</b>
            </h5>
            <p class="textHeight">Aquí puedes generar un informe con la información publica de los inquilinos </p>
            <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background:rgb(6, 127, 202);border-radius: 20px;"
                    href="#"
                >
                    Informe
                    <!--<i class="material-icons  text-white large rounded-circle">demography</i>-->
                    <span class="material-symbols-sharp text-white  btn p-2 text-center ">
                    demography
                    </span>
            </a>
            <!--form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form-->
        </div>
    </div>
    
    
    </div>
    <img src="/img/ellipse11.png" alt="" 
        style="position: absolute; width: 1616px; height: 1148px; left: 100px; bottom: -900px; z-index: -1;"
    >
  
</main>
{% endblock %}